# -*- coding: utf-8 -*-
"""Assignment_3_notebook.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17KhcCIMHzeARPks82c2T_Rgk3PRslREo

**Import** *and* setup some auxiliary functions
"""

# Don't edit this cell
import os
import timeit
import time
import numpy as np
from collections import OrderedDict
from pprint import pformat
from tqdm import tqdm
from google.colab import drive

import torch
import torch.nn as nn
import torch.nn.init as init
import torch.nn.functional as F
import torch.backends.cudnn as cudnn
from torch.utils.data.sampler import *
from torchvision import transforms, datasets
import torch.optim.lr_scheduler as lr_anneal
from torch.utils.data import Subset

torch.multiprocessing.set_sharing_strategy('file_system')
cudnn.benchmark = True

# TODO: Main model definition + any utilities such as weight initialization or custom layers, ADD DROPOUT, BATCHNORM, SKIP CONNECTION,
class Net(nn.Module):
    def __init__(self):
      super(Net,self).__init__()
      self.pool = nn.MaxPool2d(2,2)
      self.skip = nn.Identity()

      self.conv11   = nn.Conv2d(3,16,3,padding=1)
      self.batchnorm16 = nn.BatchNorm2d(16)
      #set
      self.downsample1 = nn.Conv2d(16,32,1,stride = 2)
      self.conv12   = nn.Conv2d(16,32,3,padding=1)

      self.conv21   = nn.Conv2d(32,32,3,padding=1)
      #+
      #set
      self.downsample2 = nn.Conv2d(32,64,1,stride = 2)
      self.batchnorm32 = nn.BatchNorm2d(32)
      self.conv22   = nn.Conv2d(32,64,3,padding=1)

      self.conv31   = nn.Conv2d(64,64,3,padding=1)
      #+
      self.batchnorm64 = nn.BatchNorm2d(64)
      self.conv32   = nn.Conv2d(64,128,3,padding=1)
      self.batchnorm128 = nn.BatchNorm2d(128)
      self.fc1    = nn.Linear(128*4*4,2*2*128)
      self.fc2    = nn.Linear(2*2*128,128)
      self.fc3    = nn.Linear(128,10)
    
    def forward(self,x):
      '''
      -> Use increasing dropout 
      
      -> CNN structure for each block is like
        _. conv => batch => conv => pool =>dropout
        _. With skip connection every two conv

      -> Three fully connected layers at the end
        _. With drop out
      '''
      '''
      first cnn block
      '''
      x = F.relu(self.conv11(x))
      #batch normalization
      x = self.batchnorm16(x)
      #initial for skip connection
      skip1 = x
      skip1 = self.downsample1(skip1)
      x = F.relu(self.conv12(x))
      #maxPooling
      x = self.pool(x)
      #dropout
      x = F.dropout(x,p = 0.3)


      '''
      second cnn block
      '''
      x = F.relu(self.conv21(x))
      #skip connection
      x = x+skip1
      x = self.batchnorm32(x)
      skip2 = x
      ship2 = self.downsample2(skip2)
      #print("skip2 shape",skip2.shape)
      x = F.relu(self.conv22(x))
      x = self.pool(x)#may pool
      x = F.dropout(x,p = 0.4)


      '''
      third cnn block
      '''
      x = F.relu(self.conv31(x))
      #print("shape is",x.shape)
      #x = x+skip2 
      x = self.batchnorm64(x)
      x = F.relu(self.conv32(x))
      x = self.batchnorm128(x)
      x = self.pool(x)
      x = F.dropout(x,p = 0.5)


      '''
      Flatten to fully connected layers
      '''
      #print(x.shape)
      #flatten the layers
      x = x.view(-1,128*4*4)
      #First fully connected layer
      x = F.relu(self.fc1(x))
      x = F.dropout(x,p = 0.5)
      x = F.relu(self.fc2(x))
      x = self.fc3(x)

      return x

cnn = Net()

# TODO: Cifar-10 dataloading
def load_data(config):
    """
    Load cifar-10 dataset using torchvision, take the last 5k of the training data to be validation data
    """
    transform_train = transforms.Compose([
        transforms.RandomCrop(32, padding=4),
        transforms.RandomHorizontalFlip(),
        transforms.ToTensor(),
        transforms.Normalize((0.4914, 0.4822, 0.4465), (0.2023, 0.1994, 0.2010)),
    ])

    transform_test = transforms.Compose([
        transforms.ToTensor(),
        transforms.Normalize((0.4914, 0.4822, 0.4465), (0.2023, 0.1994, 0.2010)),
    ])

    cifar10_training = datasets.CIFAR10(root='./CIFAR10_dataset', train=True,
                      download=True, transform=transform_train)
    # training set
    cifar10_training_set = Subset(
        cifar10_training, range(len(cifar10_training)-5000))
    # validation set
    cifar10_validation_set = Subset(
        cifar10_training, range(len(cifar10_training)-5000,len(cifar10_training)))
    # test set
    cifar10_test_set = datasets.CIFAR10(root='./CIFAR10_dataset', train=False,
                      download=True, transform=transform_test)
    #in config
    batch_size_train = config['batch_size']
    

    #dataloaders
    train_dataloader = torch.utils.data.DataLoader(
            cifar10_training_set, batch_size=batch_size_train, shuffle=True, num_workers=2)
    #
    valid_dataloader = torch.utils.data.DataLoader(
        cifar10_validation_set, batch_size=batch_size_train, shuffle=True, num_workers=2)\
    #
    test_dataloader = torch.utils.data.DataLoader(
        cifar10_test_set, batch_size=1, shuffle=True, num_workers=2)

    return train_dataloader, valid_dataloader, test_dataloader

# TODO : Main trainig + validation, returns the final model, save your best checkpoint based on the best validation accuracy
def train(trainloader, valid_dataloader, device, config):
     
    #hyperparameters
    epoch = config['num_epochs']
    lr = config['lr']
    momentum = config['momentum']
    decay = config['regular_constant']
    cnn.to(device)
    
    criterion = nn.CrossEntropyLoss()
    optimizer = torch.optim.SGD(cnn.parameters(),
            lr=lr,momentum=momentum,weight_decay=decay)
    #learning rate annealing
    scheduler = lr_anneal.StepLR(optimizer,step_size=15,gamma=0.1)
    #initialize a accuracy to be saved for 
    best_acc=0.80
    #training
    for u in range(epoch):
      cnn.train()

      for batch_idx,(data,target) in enumerate(trainloader):
        data  = data.to(device)
        target = target.to(device)
        optimizer.zero_grad()
        output = cnn(data).to(device)
        loss = criterion(output,target)
        loss.backward()
        optimizer.step()
      print("epoch version: ",(u+1))


      
      #validating
      cnn.eval()
      
      mean_acc = 0
      total = 0
      correct = 0
      #validate every 3 epoch
      if (u+1)%3 ==0:
        with torch.no_grad():
          for data,target in valid_dataloader:
            data = data.to(device)
            target = target.to(device)
            output = cnn(data).to(device)
            _,predicted = torch.max(output,dim=1)
            total += target.size(0)
            correct += (predicted==target).sum().item()
    # your code here
      if total!=0:
        mean_acc = correct/total
        print(mean_acc)
      
      #save accuracy to save best model 
      if mean_acc >0.80 and mean_acc>best_acc:
        print("=================================="\
                    "Current Model Saved"\
              "==================================")
        
        #save model to file
        if not os.path.isdir('checkpoint'):
          os.mkdir('checkpoint')
        torch.save(cnn.state_dict(), './checkpoint/ckpt.pth')
        best_acc = mean_acc
      
      #lr anneal
      scheduler.step()
      
    return cnn

def save_model_colab_for_submission(model):  # if you are running on colab
  drive.mount('/content/gdrive/', force_remount=True)
  torch.save(model.to(torch.device("cpu")), '/content/gdrive/My Drive/model.pt') # you will find the model in your home drive
  
def save_model_local_for_submission(model):  # if you are running on your local machine
  torch.save(model.to(torch.device("cpu")), 'model.pt')

#TODO: Implement testing
def test(net, testloader, device):
    correct = 0
    total = 0
    ###
    net.eval()

    with torch.no_grad():
      for data,target  in testloader:
        data = data.to(device)
        target = target.to(device)
        output = net(data)
        _,predicted = torch.max(output,dim=1)

        total += target.size(0)
        correct +=(predicted==target).sum().item()

    return 100.*correct/total, correct, total

def run():
  # set parameters cifar10
  config = {
        'lr': 0.01,
        'num_epochs': 100,
        'batch_size': 128,
        'num_classes': 10,
        'momentum':0.98,
        'regular_constant': 3e-3,
       }
    
  device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
  
  train_dataloader, valid_dataloader, test_dataloader = load_data(config)
  
  model = train(train_dataloader, valid_dataloader, device, config)
  
  # Testing and saving for submission
  device = torch.device("cpu")
  
  assert os.path.isdir('checkpoint'), 'Error: no checkpoint directory found!'
  checkpoint = torch.load('./checkpoint/ckpt.pth')
  model.load_state_dict(checkpoint)
  
  model.eval()
  
  start_time = timeit.default_timer()
  test_acc, test_correct, test_total = test(model.to(device), test_dataloader, device)
  end_time = timeit.default_timer()
  test_time = (end_time - start_time)
  
  save_model_colab_for_submission(model)

  return test_acc, test_correct, test_time

"""Main loop. Run time and total score will be shown below."""

# Don't edit this cell
def compute_score(acc, min_thres=65, max_thres=80):
  # Your Score thresholds
  if acc <= min_thres:
    base_score = 0.0
  elif acc >= max_thres:
    base_score = 100.0
  else:
    base_score = float(acc - min_thres) / (max_thres - min_thres) * 100
  return base_score

def main():
    
  accuracy, correct, run_time = run()
  
  score = compute_score(accuracy)
  
  result = OrderedDict(correct=correct,
                        accuracy=accuracy,
                        run_time=run_time,
                        score=score)
  
  with open('result.txt', 'w') as f:
      f.writelines(pformat(result, indent=4))
  print("\nResult:\n", pformat(result, indent=4))


main()