# -*- coding: utf-8 -*-
"""Assignment_4_StudentID.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1swqK9_vk86K2-_iHAc9T_cO7_4xx03oM
"""

import numpy as np
import cv2
import os
from keras.datasets import mnist
import matplotlib.pyplot as plt
from tqdm import tqdm
from torchvision import transforms
import torch.nn as nn
from torch.utils.data import DataLoader,Dataset
import torch
import torch.optim as optim
from torch.autograd import Variable
from sklearn.model_selection import train_test_split

"""# Utils"""

def add_noise(imgs):
    """
    Main function add noise to images.

    Here we load the dataset, add gaussian, poisson, speckle
    'gauss'     Gaussian-distributed additive noise.
    'speckle'   Multiplicative noise using out = image + n*image,where
                n is uniform noise with specified mean & variance.
    """
    row, col = 28, 28
    noisy_output = np.zeros((len(imgs), row, col))
    
    # adding noise
    for idx, img in enumerate(imgs):
        img = img.astype(np.float32)
        noise_type = random.choice(["gaussian", "speckle"])

        if noise_type == "gaussian":
            mean, var = -10, 100
            sigma = var**.5
            noise = np.random.normal(20, 10, img.shape)
            img += noise

        elif noise_type == "speckle":
            noise = np.random.randn(row,col)
            noise = noise.reshape(row,col)
            img += img * noise


        noisy_output[idx] = img
        
    return noisy_output

"""# Load and Split Data"""

# Loading the dataset from Keras
(xtrain, ytrain), (xtest, ytest) = mnist.load_data()
xtrain, xval, ytrain, yval = train_test_split(xtrain, ytrain, test_size=10000, random_state=42)

print(f"Number of Training Set datapoints: {len(xtrain)}")
print(f"Number of Validation Set datapoints: {len(xval)}")
print(f"Number of Test Set datapoints: {len(xtest)}")

"""## Add Noise"""

"""
Split Data and Add Noise

We split the 50k training data into 2 sets where we add 1 type of noise to each set. 
"""
import random

# We define two types of noises
noise_types = ["gaussian","speckle"]

# adding noise to xtrain and xtest
noisy_xtrain = add_noise(xtrain)
noisy_xval = add_noise(xval)
noisy_xtest = add_noise(xtest)

"""## Visualize Noise"""

"""
Visualization of Original Image vs. Noisy Image.
"""
import itertools
f, axes = plt.subplots(5, 10, figsize=(16, 10))

for xid, yid in itertools.product(range(5), range(0, 10, 2)):
    image_id = random.randint(0, 50000)
    
    # display original image
    axes[xid, yid].imshow(xtrain[image_id],cmap="gray")
    axes[xid, yid].set(xticks = [], yticks = [])

    # display original image
    axes[xid, yid+1].imshow(noisy_xtrain[image_id],cmap="gray")
    axes[xid, yid+1].set(xticks = [], yticks = [])
    
    if xid == 0:
        axes[xid, yid].set(title = "Original")
        axes[xid, yid+1].set(title = "Noisy")

"""## Data Loader"""

"""
Dataset
"""
class noisedDataset(Dataset):
  
    def __init__(self, noisy_dataset, clean_dataset, labels, transform):
        self.noise = noisy_dataset
        self.clean = clean_dataset
        self.labels = labels
        self.transform = transform
  
    def __len__(self):
        return len(self.noise)
  
    def __getitem__(self,idx):
        noisy_x = self.noise[idx]
        clean_x = self.clean[idx]
        y = self.labels[idx]
    
        if self.transform != None:
            noisy_x = self.transform(noisy_x)
            clean_x = self.transform(clean_x)

        return (noisy_x, clean_x, y)

tsfms = transforms.Compose([
    transforms.ToTensor()
])

trainset = noisedDataset(noisy_xtrain, xtrain, ytrain, tsfms)
valset = noisedDataset(noisy_xval, xval, yval, tsfms)
testset = noisedDataset(noisy_xtest, xtest, ytest, tsfms)

batch_size = 32

train_dataloader = DataLoader(trainset, batch_size=32, shuffle=True)
val_dataloader = DataLoader(valset, batch_size=1, shuffle=True)
test_dataloader = DataLoader(testset, batch_size=1, shuffle=True)
print(enumerate(train_dataloader))

"""# Denoising Autoencoder (DAE) Model"""

"""
Autoencoder model
"""
# TODO: Main model definition + any utilities or custom layers
class DAE(nn.Module):
    # ---------- TODO: code here ------------ #
    def __init__(self):
        super(DAE,self).__init__()
        self.encoder = nn.Sequential(
            nn.Linear(28*28,512),
            nn.ReLU(True),
            nn.Linear(512,256),
            nn.ReLU(True),
            nn.Linear(256,64),
            nn.ReLU(True),
      )
        self.decoder = nn.Sequential(
            nn.Linear(64,256),
            nn.ReLU(True),
            nn.Linear(256,512),
            nn.ReLU(True),
            nn.Linear(512,28*28),
            
      )
    def forward(self,x):
        #print(x.shape)
        encode = self.encoder(x)
        decode = self.decoder(encode)

        return decode


model = DAE()

"""# Training"""

"""
Main Train Script
"""
#torch.Size([32, 1, 28, 28])

def train(train_dataloader, val_dataloader, device, config):
    if torch.cuda.is_available()==True:
      print("is training on gpu")
    else:
      print("something is wrong")
    model = DAE().to(device)
    # epochs_loss is losses for epochs --> len(epochs_loss) = number of epochs
    epochs_loss = []
    

    # ---------- TODO: code here ------------ #
    criterion = nn.MSELoss()
    optimizer = torch.optim.SGD(model.parameters(),lr=config['lr'],weight_decay=config['weight_decay'],momentum=config['momentum'])


    for epoch in range(config['num_epochs']):
        model.train()
        for noisy,original,target in tqdm(train_dataloader,position=0):
      
        #flatten to use fully connected layers
            noisy = noisy.view(noisy.size(0),-1).type(torch.FloatTensor).to(device)
            original = original.view(original.size(0),-1).type(torch.FloatTensor).to(device)
        #target = target.view(target.size(0),-1).type(torch.FloatTensor)
            output = model(noisy)
            loss  = criterion(output,original)
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
        print("epoch is",(epoch+1))
        print("loss is",loss.item())
      
        
        validation_loss = 0

        model.eval()
        with torch.no_grad():
            for (noisy,original,target) in val_dataloader:
                noisy = noisy.view(noisy.size(0),-1).type(torch.FloatTensor).to(device)
                original = original.view(original.size(0),-1).type(torch.FloatTensor).to(device)
                output = model(noisy)
                validation_loss += criterion(output,original).item()
            validation_loss /= len(val_dataloader.dataset)
            print(validation_loss)
            epochs_loss.append(validation_loss)
    return model, epochs_loss 

"""
Saving Model Script
"""
def save_model_local_for_submission(model):  # if you are running on your local machine
    torch.save(model.to(torch.device("cpu")), 'checkpoint/model.pt')

"""# Run"""

def run():
    # set parameters
    config = {
        'num_epochs': 100,
        'lr': 1e-3,
        'weight_decay':3e-3,
        'momentum' : 0.98,
    }

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model, epochs_loss = train(train_dataloader, val_dataloader, device, config)
    
    # save model in checkpoint dir
    assert os.path.isdir('checkpoint'), 'Error: no checkpoint directory found!'
    save_model_local_for_submission(model)
    
    return model, epochs_loss

def main():
    
    model, epochs_loss = run()
    
    # plot loss in each epoch
    plt.plot(range(len(epochs_loss)), epochs_loss)
    plt.xlabel('Epochs')
    plt.ylabel('Epochs Loss')
    
    return model
    
model = main()

"""# Visualize Denoising Test Set"""

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

f, axes= plt.subplots(6, 3, figsize = (5, 10))
axes[0,0].set_title("Original Image")
axes[0,1].set_title("Noisy Image")
axes[0,2].set_title("Cleaned Image")

for idx, (noisy, clean, label) in enumerate(test_dataloader):
    if idx > 5:
        break
    
    # denoising with DAE
    noisy = noisy.view(noisy.size(0),-1).type(torch.FloatTensor)
    
    # this line must be commented to avoid illegal memory access error
    # noisy = noisy.to(device)
    output = model(noisy)
    
    # fix size
    output = output.view(1, 28, 28)
    output = output.permute(1, 2, 0).squeeze(2)
    output = output.detach().cpu().numpy()
    
    noisy = noisy.view(1, 28, 28)
    noisy = noisy.permute(1, 2, 0).squeeze(2)
    
    # this line must be commented to avoid illegal memory access error
    # noisy = noisy.detach().cpu().numpy()

    clean = clean.view(1, 28, 28)
    clean = clean.permute(1, 2, 0).squeeze(2)
    clean = clean.detach().cpu().numpy()
    
    # plot
    axes[idx, 0].imshow(clean, cmap="gray")
    axes[idx, 1].imshow(noisy, cmap="gray")
    axes[idx, 2].imshow(output, cmap="gray")
    
    axes[idx, 0].set(xticks=[], yticks=[])
    axes[idx, 1].set(xticks=[], yticks=[])
    axes[idx, 2].set(xticks=[], yticks=[])

"""# Evaluation with Peak Signal to Noise Ratio (PSNR) Metric"""

def evaluate(model, test_dataloader):
    psnr_noisy = []
    psnr_clean = []
    for noisy, original, label in tqdm(test_dataloader):
        # denoising with DAE
        noisy = noisy.view(noisy.size(0),-1).type(torch.FloatTensor)
        
        # this line must be commented to avoid illegal memory access error
        # noisy = noisy.to(device)
        clean = model(noisy)

        # fix size
        clean = clean.view(1, 28, 28)
        clean = clean.permute(1, 2, 0).squeeze(2)
        clean = clean.detach().cpu().numpy()

        noisy = noisy.view(1, 28, 28)
        noisy = noisy.permute(1, 2, 0).squeeze(2)
        noisy = noisy.detach().cpu().numpy()

        original = original.view(1, 28, 28)
        original = original.permute(1, 2, 0).squeeze(2)
        original = original.detach().cpu().numpy()
        
        psnr_noisy.append(cv2.PSNR(noisy, original))
        psnr_clean.append(cv2.PSNR(clean, original))
        
    return np.mean(psnr_noisy), np.mean(psnr_clean)

psnr_noisy, psnr_clean = evaluate(model, test_dataloader)

print(f'PSNR improved from {psnr_noisy} for Noisy Images to {psnr_clean} for denoised images by DAE.')